Read data from xlsx to dataframe and check to see several rows of it

In [91]:
import pandas as pd

df = pd.read_excel('../data/raw/nuclear_safety_q4_2025.xlsx')

df.head()

,year,quarter,station,irg,irg_index,iodine_ radionuclides,iodine_ radionuclides_index,stable_radionuclides,stable_ radionuclides_index,cs_137_emission,co_60_ emission,cs_137_dump,co_60_dump,volume,index_radioactive_releas,index_dump
0,2018,1,ЗАЕС,89.0,0.13,260.0,"<0,01",650.0,0.03,1980.0,1020.0,4330.0,3670.0,833000.0,0.149,0.33
1,2018,1,РАЕС,105.0,0.16,147.0,"<0,01",269.0,0.07,587.0,165.0,4800.0,620.0,2220000.0,0.780,0.096
2,2018,1,ЮУАЕС,45.0,0.10,76.0,"<0,01",116.0,0.02,136.0,373.0,390.0,370.0,14600.0,0.136,0.284
3,2018,1,ХАЕС,31.0,0.07,26.8,"<0,01",37.5,"<0,01",29.4,13.8,380.0,NaN,22070.0,0.110,0.03
4,2018,2,ЗАЕС,84.0,0.12,262.0,"<0,01",640.0,0.03,453.0,1003.0,4627.0,3432.0,812667.0,0.115,0.91

In [92]:
df.shape

(128, 16)

Check basic statistic for columns

In [93]:
df.describe()

,year,quarter,irg,irg_index,iodine_ radionuclides,stable_radionuclides,cs_137_emission,co_60_ emission,cs_137_dump,co_60_dump,volume,index_radioactive_releas
count,128.000000,128.000000,115.000000,115.000000,115.000000,115.000000,115.000000,115.000000,115.000000,98.000000,1.150000e+02,115.000000
mean,2021.500000,2.500000,67.106957,0.118261,85.119130,238.275652,237.293913,320.064348,3973.660870,1300.782755,1.025583e+06,1.044730
std,2.300291,1.122427,41.597420,0.059150,85.677601,199.293961,356.340647,438.618397,4778.517156,1681.422302,1.377303e+06,1.339668
min,2018.000000,1.000000,21.000000,0.050000,15.000000,27.600000,11.200000,12.000000,67.000000,2.210000,1.480000e+03,0.070000
25%,2019.750000,1.750000,31.000000,0.070000,32.000000,39.000000,33.000000,50.000000,578.000000,219.000000,2.223500e+04,0.200000
50%,2021.500000,2.500000,50.000000,0.100000,64.000000,219.000000,89.000000,201.000000,2109.000000,668.000000,6.584000e+04,0.600000
75%,2023.250000,3.250000,97.500000,0.150000,84.500000,296.500000,296.500000,412.500000,5220.500000,1522.750000,2.627025e+06,0.915000
max,2025.000000,4.000000,205.000000,0.340000,552.000000,754.000000,2115.000000,3639.000000,20248.000000,9000.000000,4.469170e+06,4.967000

Check for null values

In [94]:
df.isna().sum()

year                            0
quarter                         0
station                         0
irg                            13
irg_index                      13
iodine_ radionuclides          13
iodine_ radionuclides_index    13
stable_radionuclides           13
stable_ radionuclides_index    13
cs_137_emission                13
co_60_ emission                13
cs_137_dump                    13
co_60_dump                     30
volume                         13
index_radioactive_releas       13
index_dump                     13
dtype: int64

The data about ЗАЕС after 2022 is missing, that explains the 13 missing values in each column.

Also co_60_dump at ХАЕС is always missing.

So let's delete rows about ЗАЕС after 2022.

In [95]:
# Create masks for each condition
mask1 = (df['station'] == 'ЗАЕС') & (df['year'] > 2022)
mask2 = (df['station'] == 'ЗАЕС') & (df['year'] == 2022) & (df['quarter'] == 4)

# Combine masks with OR (|) and then invert with NOT (~)
filtered_df = df[~(mask1 | mask2)]
filtered_df

,year,quarter,station,irg,irg_index,iodine_ radionuclides,iodine_ radionuclides_index,stable_radionuclides,stable_ radionuclides_index,cs_137_emission,co_60_ emission,cs_137_dump,co_60_dump,volume,index_radioactive_releas,index_dump
0,2018,1,ЗАЕС,89.0,0.13,260.0,"<0,01",650.0,0.03,1980.0,1020.0,4330.0,3670.0,833000.0,0.149,0.33
1,2018,1,РАЕС,105.0,0.16,147.0,"<0,01",269.0,0.07,587.0,165.0,4800.0,620.0,2220000.0,0.780,0.096
2,2018,1,ЮУАЕС,45.0,0.10,76.0,"<0,01",116.0,0.02,136.0,373.0,390.0,370.0,14600.0,0.136,0.284
3,2018,1,ХАЕС,31.0,0.07,26.8,"<0,01",37.5,"<0,01",29.4,13.8,380.0,NaN,22070.0,0.110,0.03
4,2018,2,ЗАЕС,84.0,0.12,262.0,"<0,01",640.0,0.03,453.0,1003.0,4627.0,3432.0,812667.0,0.115,0.91
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122,2025,3,ПАЕС,25.0,0.06,73.0,"<0,01",112.0,0.01,41.0,148.0,878.0,879.0,34500.0,4.267,2.787
123,2025,3,ХАЕС,30.0,0.07,36.0,"<0,01",37.0,"<0,01",31.0,24.0,176.0,11.0,20008.0,0.840,0.098
125,2025,4,РАЕС,131.0,0.22,17.0,"<0,01",256.0,0.06,225.0,77.0,3743.0,855.0,2903600.0,0.380,0.43
126,2025,4,ПАЕС,40.0,0.09,67.0,"<0,01",100.0,0.01,23.0,77.0,159.0,154.0,6200.0,4.193,2.868
127,2025,4,ХАЕС,26.0,0.06,33.0,"<0,01",33.0,"<0,01",28.0,30.0,110.0,4.0,7744.0,0.610,0.101

In [96]:
df.dtypes

year                             int64
quarter                          int64
station                            str
irg                            float64
irg_index                      float64
iodine_ radionuclides          float64
iodine_ radionuclides_index        str
stable_radionuclides           float64
stable_ radionuclides_index     object
cs_137_emission                float64
co_60_ emission                float64
cs_137_dump                    float64
co_60_dump                     float64
volume                         float64
index_radioactive_releas       float64
index_dump                      object
dtype: object

There is some columns with '<0.01' or something like that, it prevents from treating these columns as numerical

So lets delete '<' and convert types

In [97]:
# First remove '<' symbols
df = df.replace('<', '', regex=True)

# Then convert all columns to numeric where possible
for col in df.columns:
    df[col] = pd.to_numeric(df[col], errors='coerce')

df.head()

,year,quarter,station,irg,irg_index,iodine_ radionuclides,iodine_ radionuclides_index,stable_radionuclides,stable_ radionuclides_index,cs_137_emission,co_60_ emission,cs_137_dump,co_60_dump,volume,index_radioactive_releas,index_dump
0,2018,1,NaN,89.0,0.13,260.0,NaN,650.0,0.03,1980.0,1020.0,4330.0,3670.0,833000.0,0.149,0.330
1,2018,1,NaN,105.0,0.16,147.0,NaN,269.0,0.07,587.0,165.0,4800.0,620.0,2220000.0,0.780,0.096
2,2018,1,NaN,45.0,0.10,76.0,NaN,116.0,0.02,136.0,373.0,390.0,370.0,14600.0,0.136,0.284
3,2018,1,NaN,31.0,0.07,26.8,NaN,37.5,NaN,29.4,13.8,380.0,NaN,22070.0,0.110,0.030
4,2018,2,NaN,84.0,0.12,262.0,NaN,640.0,0.03,453.0,1003.0,4627.0,3432.0,812667.0,0.115,0.910

In [98]:
df.dtypes

year                             int64
quarter                          int64
station                        float64
irg                            float64
irg_index                      float64
iodine_ radionuclides          float64
iodine_ radionuclides_index    float64
stable_radionuclides           float64
stable_ radionuclides_index    float64
cs_137_emission                float64
co_60_ emission                float64
cs_137_dump                    float64
co_60_dump                     float64
volume                         float64
index_radioactive_releas       float64
index_dump                     float64
dtype: object

Data is cleaned, save it for further use

In [99]:
df.to_csv('../data/raw/clean_data.csv')